apiVersion: v1
kind: Pod
metadata:
  name: nginx11
  labels:
   tier: frondend
   app-name: website
spec:
   containers:
   - name: nginx1
     image: nginx:1.14.2
     ports:
       - containerPort: 80